"""
Sky Defender - 配置常量
"""
import pygame

# 屏幕设置
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 720
FPS = 60

# 颜色
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 50, 50)
COLOR_GREEN = (50, 255, 50)
COLOR_BLUE = (50, 100, 255)
COLOR_YELLOW = (255, 255, 50)
COLOR_CYAN = (50, 255, 255)
COLOR_MAGENTA = (255, 50, 255)
COLOR_ORANGE = (255, 150, 50)
COLOR_PURPLE = (180, 50, 255)
COLOR_GRAY = (150, 150, 150)
COLOR_DARK_GRAY = (50, 50, 50)

# 玩家设置
PLAYER_BASE_SPEED = 5
PLAYER_BASE_HP = 100
PLAYER_INVINCIBLE_TIME = 120  # 帧

# 武器类型
WEAPON_MACHINE_GUN = 0
WEAPON_SHOTGUN = 1
WEAPON_LASER = 2
WEAPON_MISSILE = 3
WEAPON_PLASMA = 4

WEAPON_NAMES = {
    WEAPON_MACHINE_GUN: "机关枪",
    WEAPON_SHOTGUN: "散弹枪",
    WEAPON_LASER: "激光炮",
    WEAPON_MISSILE: "追踪导弹",
    WEAPON_PLASMA: "等离子球",
}

# 升级类型
UPGRADE_FIRE_RATE = 0
UPGRADE_DAMAGE = 1
UPGRADE_BULLET_SPEED = 2
UPGRADE_MULTISHOT = 3
UPGRADE_MOVE_SPEED = 4
UPGRADE_MAX_HP = 5
UPGRADE_REGEN = 6
UPGRADE_CRIT_CHANCE = 7
UPGRADE_MAGNET = 8
UPGRADE_WINGMAN = 9
UPGRADE_SHIELD = 10
UPGRADE_BULLET_SIZE = 11

UPGRADE_NAMES = {
    UPGRADE_FIRE_RATE: "射速提升",
    UPGRADE_DAMAGE: "伤害强化",
    UPGRADE_BULLET_SPEED: "弹速提升",
    UPGRADE_MULTISHOT: "多重射击",
    UPGRADE_MOVE_SPEED: "引擎强化",
    UPGRADE_MAX_HP: "装甲加固",
    UPGRADE_REGEN: "自动修复",
    UPGRADE_CRIT_CHANCE: "暴击系统",
    UPGRADE_MAGNET: "磁力吸引",
    UPGRADE_WINGMAN: "僚机支援",
    UPGRADE_SHIELD: "能量护盾",
    UPGRADE_BULLET_SIZE: "弹药扩容",
}

# 敌人类型
ENEMY_SMALL = 0
ENEMY_MEDIUM = 1
ENEMY_LARGE = 2
ENEMY_FAST = 3
ENEMY_SHOOTER = 4
ENEMY_TANK = 5

# BOSS类型
BOSS_INTERCEPTOR = 0
BOSS_DESTROYER = 1
BOSS_MOTHERSHIP = 2
BOSS_CRUSHER = 3
BOSS_PHANTOM = 4

# 道具类型
DROP_COIN = 0
DROP_HP = 1
DROP_NUKE = 2
DROP_POWER = 3

# 游戏状态
STATE_MENU = 0
STATE_PLAYING = 1
STATE_PAUSED = 2
STATE_UPGRADE = 3
STATE_GAME_OVER = 4
STATE_VICTORY = 5
STATE_SHOP = 6  # 商店状态
STATE_HELP = 7  # 帮助页面

# 总关卡数
MAX_LEVEL = 100
BOSS_LEVEL_INTERVAL = 10

# 技能类型
SKILL_ENERGY_CANNON = 0  # 能量炮 - 高伤害直线穿透
SKILL_SCREEN_CLEAR = 1   # 全屏清怪 - 秒杀所有普通敌人，BOSS掉血

SKILL_NAMES = {
    SKILL_ENERGY_CANNON: "能量炮",
    SKILL_SCREEN_CLEAR: "全屏冲击",
}

SKILL_COOLDOWN = {
    SKILL_ENERGY_CANNON: 600,  # 10秒 (60fps)
    SKILL_SCREEN_CLEAR: 1800,  # 30秒
}

SKILL_CHARGE_MAX = 100  # 能量最大值
